// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/trending": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/suggested": {
    params: {};
  };
  "/following": {
    params: {};
  };
  "/post-job": {
    params: {};
  };
  "/manage-jobs": {
    params: {};
  };
  "/applicants": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/trending" | "/history" | "/suggested" | "/following" | "/post-job" | "/manage-jobs" | "/applicants";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/home-redirect.tsx": {
    id: "routes/home-redirect";
    page: "/home";
  };
  "routes/trending.tsx": {
    id: "routes/trending";
    page: "/trending";
  };
  "routes/history.tsx": {
    id: "routes/history";
    page: "/history";
  };
  "routes/suggested.tsx": {
    id: "routes/suggested";
    page: "/suggested";
  };
  "routes/following.tsx": {
    id: "routes/following";
    page: "/following";
  };
  "routes/post-job.tsx": {
    id: "routes/post-job";
    page: "/post-job";
  };
  "routes/manage-jobs.tsx": {
    id: "routes/manage-jobs";
    page: "/manage-jobs";
  };
  "routes/applicants.tsx": {
    id: "routes/applicants";
    page: "/applicants";
  };
};